-- 1.NAME, INITIALS and number of sets won for each player
SELECT PLAYERS.NAME, PLAYERS.INITIALS, sum(MATCHES.WON)
from PLAYERS
Join MATCHES On PLAYERS.PLAYERNO = MATCHES.PLAYERNO
group by PLAYERS.NAME, PLAYERS.INITIALS;

-- 2.NAME, PEN_DATE and AMOUNT sorted in descending order by AMOUNT
SELECT PLAYERS.NAME, PENALTIES.PEN_DATE , PENALTIES.AMOUNT from PLAYERS join PENALTIES on PLAYERS.PLAYERNO = PENALTIES.PLAYERNO order by AMOUNT;

-- 3.TEAMNO, NAME (of the captain) per team
SELECT  TEAMNO, NAME from TEAMS join PLAYERS on TEAMS.PLAYERNO = PLAYERS.PLAYERNO;
-- 4.NAME (player name), WON, LOST of all won matches
SELECT  NAME,  WON, LOST from PLAYERS join MATCHES on PLAYERS.PLAYERNO = MATCHES.PLAYERNO;