Select JOBS.JOB_ID, JOB_TITLE, sum(SALARY)
from JOBS
         join EMPLOYEES on JOBS.JOB_ID = EMPLOYEES.JOB_ID
group by JOBS.JOB_ID, JOB_TITLE
order by sum(SALARY) desc;

SELECT avg(SALARY)
from EMPLOYEES
         join JOBS on EMPLOYEES.JOB_ID = JOBS.JOB_ID
where JOB_TITLE != 'President';

SELECT FIRST_NAME, LAST_NAME, JOB_TITLE
from EMPLOYEES
         join JOBS on EMPLOYEES.JOB_ID = JOBS.JOB_ID;

SELECT DEPARTMENT_NAME, POSTAL_CODE, CITY, STATE_PROVICE, STREET_ADDRESS
from DEPARTMENTS
         join LOCATIONS on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

SELECT DEPARTMENT_NAME,
       POSTAL_CODE,
       CITY,
       STATE_PROVICE,
       STREET_ADDRESS,
       COUNTRY_NAME,
       (FIRST_NAME || ' ' || LAST_NAME) as Manager
from DEPARTMENTS
         join LOCATIONS on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
         join COUNTRIES on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
         join EMPLOYEES on DEpartments.MANAGER_ID = EMPLOYEE_ID;


Select (FIRST_NAME ||' ' || LAST_NAME) as Name, JOB_TITLE as Job, SALARY, DEPARTMENT_NAME from  EMPLOYEES join jobs on EMPLOYEES.JOB_ID = jobs.JOB_ID join DEPARTMENTS on  EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

Select LPAD('->',LEVEL *10)|| FIRST_NAME|| LAST_NAME from EMPLOYEES start with  JOB_ID = (Select JOB_ID from JOBS where JOB_TITLE = 'President') connect by prior EMPLOYEE_ID = MANAGER_ID;