--1-6 Tennis query

--Select TEAMNO from  TEAMS where
SELECT  PLAYERS.PLAYERNO, PLAYERS.NAME, PLAYERS.INITIALS, MATCHES.WON from  PLAYERS, MATCHES where PLAYERS.PLAYERNO = MATCHES.PLAYERNO and matches.WON > 0;