--1-6 Tennis query

Select TEAMNO from  TEAMS where PLAYERNO != 27;
SELECT  PLAYERS.PLAYERNO, PLAYERS.NAME, PLAYERS.INITIALS, MATCHES.WON from  PLAYERS, MATCHES where PLAYERS.PLAYERNO = MATCHES.PLAYERNO and matches.WON > 0;
SELECT  distinct PLAYERS.playerno, PLAYERS.name from PLAYERS, PENALTIES WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO;
SELECT  distinct PLAYERS.playerno, PLAYERS.name from PLAYERS, PENALTIES WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO and PENALTIES.AMOUNT >50;
select  PLAYERNO, NAME from PLAYERS where YEAR_OF_BIRTH = (SELECT  YEAR_OF_BIRTH from PLAYERS where  NAME = 'Parmenter' and INITIALS = 'R');
SELECT  PLAYERNO, NAME from PLAYERS where YEAR_OF_BIRTH = (Select  min(YEAR_OF_BIRTH) from PLAYERS where TOWN = 'Stratford');

